### ISSUE TITLE
add example how to run buildscript of a different branch

### ISSUE THREAD

**Issue by Londane** [mserranom/bbrun#10]
At the moment I am at a feature branch, say "feature-1".
But I want to test the scripts for a different branch, say "dev".

I tried 
`bbrun --pipline branches:dev`
and 
`bbrun --pipline dev`

but only the default scripts will be executed.

The `bitbucket-pipelines.yml` looks like:
```
image: node:6.10.3
clone: 
  depth: 5
pipelines: 
     
  branches:
    dev:
     -step:
        scripts:
          - echo dev
    master:
     -step:
        scripts:
          - echo master
    default:
     -step:
        scripts:
          - echo default
```
Can you explain how i can tell `bbrun` to excute the dev scripts ? 
Thank you for your help !
