### ISSUE TITLE
bbrun should not start steps wich are used for deployment 

### ISSUE THREAD

**Issue by tzahari** [mserranom/bbrun#45]
I started a bbrun without parameters and the fist default step was successful.
But then also another default step wich has deployment: staging & trigger: manual set.
This should be prevented!

attached you will find a test bitbucket-pipline.yml:
```
pipelines:
  default:
    - step:
        name: Build & Test
        script:
          - /bin/echo "Build & Test"
    - step:
        name: Deploy to STAGING
        deployment: staging
        trigger: manual
        script:
          - /bin/echo "Deploy to STAGING - this should not be run!"
    - step:
        name: Deploy to LIVE
        deployment: production
        trigger: manual
        script:
          - /bin/echo "Deploy to LIVE - this should not be run!"
```
