### ISSUE TITLE
Add memory constraints

### ISSUE THREAD

**Issue by mserranom** [mserranom/bbrun#5]
As in:

```
options:
  size: 2x  # all steps in this repo get 8GB memory
 
pipelines:
  default:
    - step:
        size: 2x  # or configure at step level
        script:
          - ...
```
