### ISSUE TITLE
steps.forEach is not a function 

### ISSUE THREAD

**Issue by grug7** [mserranom/bbrun#55]
returning following error `steps.forEach is not a function` when running the following

command:
```
bbrun --template test-pipelines.yml
```
test-pipelines.yml
```
image: node:10.14.1

definitions:
  caches:
    node: node_modules
  steps:
    - step: &Test
        name: Run Tests
        caches:
          - node
        script:
          - npm run test:pipeline-ob
          - npm run test:pipeline-webauth
pipelines:
  default:
    "**":
      - step: &Test
```
